---
title: "线性模型引论-程序题：补6.6"
author: "王健"
date: "2017/6/6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
x2<-c(85,92
      ,91.5
      ,92.9
      ,93
      ,96
      ,95
      ,95.6
      ,98.9
      ,101.5
      ,102
      ,105
      ,106
      ,109
      ,112
      ,112.5
      ,113
      ,114)
x3<-c(87
      ,94
      ,95
      ,95.5
      ,96
      ,97
      ,97.5
      ,98
      ,101.2
      ,102.5
      ,104
      ,105.9
      ,111
      ,110
      ,112
      ,112.3
      ,96
      ,113)
y<-c(7.8
     ,8.4
     ,8.7
     ,9
     ,9.6
     ,10.3
     ,10.6
     ,10.9
     ,11.3
     ,12.3
     ,13.5
     ,14.2
     ,14.9
     ,15.9
     ,18.5
     ,19.5
     ,19.9
     ,20.5)
fm<-lm(y~x2+x3)
fm
summary(fm)
tstep<-step(fm)
summary(tstep)
#逐步回归，已经是最优模型,选模型和原模型一致，q=3;


AIC(fm)
#按照公式计算
y<-deviance(fm)
y
aic=18*log(y)+2*3
aic
#计算aic的数值



y1<-deviance(fm)
RMS=y1/(18-3)
RMS
#计算残差平方和RMS，由于和选模型一致，因此只需除以3即为平均残差平方和准则（RMS)
#选模型的确定使用逐步回归，如果选模型和原模型不同，直接计算选模型的RMS





#计算Cp
#y=-10.43215+7.72623*x1-1.135*x2+0.1984*x3
y=x$y
y
a=x$x1
a
b=x$x2
c=x$x3
e=y-(-10.43215+0.07386*a+0.19803*b-0.05713*c)
e
w=matrix(e)
w
tw=t(w)
tw
q=tw%*%w
q
Cp=y1/q-(18-2*3)
Cp
#计算Cp统计量的数值
#综上：Cp=-11；RMS=0.45；AIC=443.74


```
